name: Hourly cron job
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
       logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
       tags:
          description: 'Test scenario tags'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: test corn
        run: |
          curl --request POST \
          --url 'https://nrankweb.vercel.app/api/user/626911d1c1ee1d99fa4f7d71'
